#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod agent;
mod backends;
mod commands;
mod memory;
mod research;
mod state;
mod tools;

use state::AppState;

fn main() {
    load_env();

    // CLI subcommands (headless).
    let args: Vec<String> = std::env::args().collect();
    if let Some(cmd) = args.get(1) {
        match cmd.as_str() {
            "selftest" => {
                run_selftest();
                return;
            }
            "ingest" => {
                run_ingest(args.get(2).map(|s| s.as_str()));
                return;
            }
            "search" => {
                let q = args[2..].join(" ");
                let rt = tokio::runtime::Runtime::new().unwrap();
                rt.block_on(async {
                    println!("provider: {}", research::provider_name());
                    match research::search(&q, 6).await {
                        Ok(rs) => {
                            println!("{} results:", rs.len());
                            for (i, r) in rs.iter().enumerate() {
                                println!("[{}] {}\n    {}", i + 1, r.title, r.url);
                            }
                            if let Some(first) = rs.first() {
                                match research::fetch_readable(&first.url, 300).await {
                                    Ok(t) => println!("\nfetched [1] ({} chars preview): {}", t.len(), t),
                                    Err(e) => println!("fetch [1] failed: {e}"),
                                }
                            }
                        }
                        Err(e) => println!("search error: {e}"),
                    }
                });
                return;
            }
            "pdftest" => {
                let out = args.get(2).map(|s| s.as_str()).unwrap_or("pdftest.pdf");
                match tools::pdf_create::generate_pdf(
                    out,
                    "Sleepers Researcher — PDF self-test",
                    "This PDF was generated by the built-in create_pdf tool.\n\nIt wraps long \
lines automatically and paginates across A4 pages. If you can read this, PDF generation works.",
                ) {
                    Ok(_) => println!("wrote {out}"),
                    Err(e) => eprintln!("pdf error: {e}"),
                }
                return;
            }
            _ => {}
        }
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .manage(AppState::new())
        .invoke_handler(tauri::generate_handler![
            commands::get_status,
            commands::get_history,
            commands::get_soul,
            commands::get_tools,
            commands::new_chat,
            commands::list_sessions,
            commands::load_session,
            commands::cancel_agent,
            commands::set_backend,
            commands::set_permissions,
            commands::chat_send,
            commands::permission_respond,
            commands::ingest_folder,
        ])
        .run(tauri::generate_context!())
        .expect("error while running Sleepers Researcher");
}

/// Load `.env` from several locations so both `cargo tauri dev` and the
/// installed app find keys. Existing env vars are not overridden.
fn load_env() {
    let _ = dotenvy::dotenv(); // walks up from cwd (dev)
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let _ = dotenvy::from_path(dir.join(".env"));
        }
    }
    let _ = dotenvy::from_path(memory::data_dir().join(".env")); // installed app
}

/// CLI: `sleepers-researcher ingest <folder>` — embed a folder into memory.
fn run_ingest(path: Option<&str>) {
    let Some(path) = path else {
        eprintln!("usage: sleepers-researcher ingest <folder>");
        return;
    };
    let rt = tokio::runtime::Runtime::new().unwrap();
    rt.block_on(async {
        let store = memory::MemoryStore::new();
        if !store.has_key() {
            eprintln!("GEMINI_API_KEY not set (needed for embeddings).");
            return;
        }
        println!("Ingesting {path} …");
        let report = memory::ingest_dir(&store, std::path::Path::new(path), |s| println!("  {s}")).await;
        println!(
            "Done. files={} chunks={} skipped={} errors={} | total memories={}",
            report.files, report.chunks, report.skipped, report.errors, store.count()
        );
    });
}

/// Headless smoke test of both backends (non-streaming + streaming).
fn run_selftest() {
    use backends::{ChatMessage, Router};
    let rt = tokio::runtime::Runtime::new().unwrap();
    rt.block_on(async {
        let router = Router::from_env();
        let prompt = vec![ChatMessage::user("Reply with exactly: hello from <your model>")];

        for name in ["gemini", "groq"] {
            println!("\n===== {name} (configured: {}) =====", router.is_configured(name));
            if !router.is_configured(name) {
                continue;
            }
            let b = router.backend(name);
            println!("model: {}", b.model());
            match b.complete(&prompt).await {
                Ok(r) => println!("complete(): {}", r.content.trim()),
                Err(e) => println!("complete() ERROR: {e}"),
            }
            let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel::<String>();
            let h = tokio::spawn(async move {
                let mut out = String::new();
                while let Some(t) = rx.recv().await {
                    out.push_str(&t);
                }
                out
            });
            match b.complete_stream(&prompt, tx).await {
                Ok(_) => println!("stream(): {}", h.await.unwrap().trim()),
                Err(e) => println!("stream() ERROR: {e}"),
            }
        }
    });
}
